[env:xiao_mbed]
platform = https://github.com/maxgerhardt/platform-nordicnrf52
board = xiaoblesense
framework = arduino
monitor_speed = 115200
monitor_filters = direct
lib_deps =
  greiman/SdFat@^2.2
  arduino-libraries/ArduinoBLE
build_flags =
  -DTARGET_SEEED_XIAO_NRF52840_SENSE
  -DARM_MATH_CM4
  -DARDUINO_ARCH_NRF52840
  -DNRF52840_XXAA
